// ==UserScript==
// @name         UBG43
// @version      2.3.0
// @namespace    https://github.com/jokeri2222
// @description  Ultra-smooth Kahoot hack with optimized neon UI
// @updateURL    https://github.com/jokeri2222/KaHack/raw/main/KaHack-Neon-Pro.meta.js
// @downloadURL  https://github.com/jokeri2222/KaHack/raw/main/KaHack-Neon-Pro.user.js
// @author       jokeri2222
// @match        https://kahoot.it/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=kahoot.it
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    const Version = '2.3.0';
    const colors = {primary:'rgba(15, 5, 30, 0.97)',secondary:'rgba(25, 10, 50, 0.95)',accent:'rgba(120, 80, 255, 0.8)',text:'#f0f0ff',correct:'hsl(155, 100%, 60%)',incorrect:'hsl(350, 100%, 65%)',close:'hsl(350, 100%, 65%)',minimize:'hsl(240, 100%, 75%)',glow:'0 0 20px rgba(120, 220, 255, 0.9)',rainbow:['#ff0080','#ff00ff','#8000ff','#0033ff','#00ffff','#00ff80','#80ff00'],particleColors:['#00ffff','#ff00ff','#ffff00']};
    let questions=[],info={numQuestions:0,questionNum:-1,lastAnsweredQuestion:-1,defaultIL:true,ILSetQuestion:-1},PPT=950,Answered_PPT=950,autoAnswer=false,showAnswers=false,inputLag=100,isAltSPressed=false,isAltHPressed=false,isAltRPressed=false,rainbowInterval=null,rainbowSpeed=300;
    const uiElement=document.createElement('div'); Object.assign(uiElement.style,{position:'fixed',top:'20px',left:'20px',width:'380px',maxHeight:'70vh',backgroundColor:colors.primary,borderRadius:'12px',boxShadow:`${colors.glow}, inset 0 0 15px rgba(100, 220, 255, 0.4)`,zIndex:'9999',overflow:'hidden',border:`1px solid ${colors.accent}`,transform:'translateZ(0)',willChange:'transform, opacity',display:'flex',flexDirection:'column'});
    const header=document.createElement('div'); Object.assign(header.style,{padding:'12px 20px',background:`linear-gradient(90deg, ${colors.secondary}, ${colors.primary})`,color:colors.text,cursor:'move',display:'flex',justifyContent:'space-between',alignItems:'center',userSelect:'none',borderBottom:`1px solid ${colors.accent}`,flexShrink:'0'});
    const title=document.createElement('div'); title.textContent='UBG43'; Object.assign(title.style,{fontWeight:'bold',fontSize:'18px',textShadow:`0 0 12px ${colors.accent}`,whiteSpace:'nowrap'});
    function createControlBtn(symbol,color){const btn=document.createElement('div');btn.textContent=symbol;Object.assign(btn.style,{width:'26px',height:'26px',background:color,color:colors.text,display:'grid',placeItems:'center',borderRadius:'50%',cursor:'pointer',fontSize:'14px',transition:'all 0.2s ease',boxShadow:`0 0 8px ${color}`,flexShrink:'0'});return btn;}
    const minimizeBtn=createControlBtn('─',colors.minimize),closeBtn=createControlBtn('✕',colors.close); const btnContainer=document.createElement('div');Object.assign(btnContainer.style,{display:'flex',gap:'8px'});btnContainer.append(minimizeBtn,closeBtn);header.append(title,btnContainer);uiElement.appendChild(header);
    const content=document.createElement('div');Object.assign(content.style,{padding:'15px',overflowY:'auto',scrollbarWidth:'thin',flexGrow:'1',display:'flex',flexDirection:'column',gap:'15px'});
    function createSection(titleText){const section=document.createElement('div');Object.assign(section.style,{background:`linear-gradient(145deg, ${colors.secondary}, ${colors.primary})`,borderRadius:'10px',padding:'15px',border:`1px solid ${colors.accent}`,boxShadow:'0 0 12px rgba(100, 220, 255, 0.2)',flexShrink:'0'});const h=document.createElement('h3');h.textContent=titleText;Object.assign(h.style,{margin:'0 0 12px 0',color:colors.text,fontSize:'16px',fontWeight:'600',textShadow:`0 0 8px ${colors.accent}`});section.appendChild(h);return{section,body:section};}
    function createInput(placeholder){const input=document.createElement('input');Object.assign(input.style,{width:'100%',padding:'10px 15px',borderRadius:'6px',border:`1px solid ${colors.accent}`,background:'rgba(0, 0, 0, 0.3)',color:colors.text,fontSize:'14px',outline:'none',transition:'all 0.3s ease',boxSizing:'border-box'});input.placeholder=placeholder;return input;}
    function createSlider(min,max,value){const container=document.createElement('div');Object.assign(container.style,{display:'flex',alignItems:'center',gap:'10px'});const slider=document.createElement('input');slider.type='range';slider.min=min;slider.max=max;slider.value=value;Object.assign(slider.style,{flex:'1',height:'6px',WebkitAppearance:'none',background:`linear-gradient(90deg, ${colors.accent}, ${colors.correct})`,borderRadius:'3px'});const valueDisplay=document.createElement('span');valueDisplay.textContent=value;Object.assign(valueDisplay.style,{color:colors.text,minWidth:'50px',textAlign:'center',textShadow:`0 0 5px ${colors.accent}`});container.append(slider,valueDisplay);return{container,slider,valueDisplay};}
    function createToggle(label,checked,onChange){const container=document.createElement('div');Object.assign(container.style,{display:'flex',justifyContent:'space-between',alignItems:'center',margin:'10px 0'});const labelEl=document.createElement('span');labelEl.textContent=label;Object.assign(labelEl.style,{color:colors.text,fontSize:'14px'});const toggle=document.createElement('label');Object.assign(toggle.style,{position:'relative',display:'inline-block',width:'50px',height:'26px'});const input=document.createElement('input');input.type='checkbox';input.checked=checked;input.style.opacity='0';const slider=document.createElement('span');Object.assign(slider.style,{position:'absolute',cursor:'pointer',top:'0',left:'0',right:'0',bottom:'0',backgroundColor:checked?colors.correct:colors.incorrect,transition:'.4s',borderRadius:'34px',boxShadow:checked?`0 0 10px ${colors.correct}`:'none'});const knob=document.createElement('span');Object.assign(knob.style,{position:'absolute',height:'20px',width:'20px',left:checked?'26px':'4px',bottom:'3px',backgroundColor:'#fff',transition:'.4s',borderRadius:'50%',boxShadow:'0 0 5px rgba(0,0,0,0.3)'});input.addEventListener('change',()=>{const c=input.checked;slider.style.backgroundColor=c?colors.correct:colors.incorrect;slider.style.boxShadow=c?`0 0 10px ${colors.correct}`:'none';knob.style.left=c?'26px':'4px';onChange(c);});slider.appendChild(knob);toggle.append(input,slider);container.append(labelEl,toggle);return container;}
    function createButton(text,onClick){const btn=document.createElement('button');btn.textContent=text;Object.assign(btn.style,{width:'100%',padding:'10px',background:`linear-gradient(145deg, ${colors.accent}, ${colors.secondary})`,color:colors.text,border:'none',borderRadius:'6px',cursor:'pointer',fontSize:'14px',fontWeight:'500',textShadow:`0 0 5px ${colors.accent}`,transition:'all 0.2s ease'});btn.addEventListener('click',()=>onClick());return btn;}
    function FindByAttributeValue(attribute,value,element_type){element_type=element_type||'*';const All=document.getElementsByTagName(element_type);for(let i=0;i<All.length;i++)if(All[i].getAttribute(attribute)===value)return All[i];return null;}
    function startRainbowEffect(){if(rainbowInterval)clearInterval(rainbowInterval);function apply(){document.querySelectorAll('button[data-functional-selector^="answer-"], button[data-functional-selector^="multi-select-button-"]').forEach(button=>{const c=colors.rainbow[Math.floor(Math.random()*colors.rainbow.length)];button.style.cssText=`background-color:${c} !important;transition:background-color ${rainbowSpeed/1000}s ease !important;`;});}apply();rainbowInterval=setInterval(apply,rainbowSpeed);}
    function stopRainbowEffect(){if(rainbowInterval){clearInterval(rainbowInterval);rainbowInterval=null;}resetAnswerColors();} function resetAnswerColors(){document.querySelectorAll('button[data-functional-selector^="answer-"], button[data-functional-selector^="multi-select-button-"]').forEach(button=>{button.style.removeProperty('background-color');button.style.removeProperty('transition');});}
    function highlightAnswers(question){if(!question)return;const buttons=document.querySelectorAll('button[data-functional-selector^="answer-"], button[data-functional-selector^="multi-select-button-"]');buttons.forEach(b=>b.style.removeProperty('background-color'));if(question.answers)question.answers.forEach(a=>{const b=FindByAttributeValue('data-functional-selector','answer-'+a,'button')||FindByAttributeValue('data-functional-selector','multi-select-button-'+a,'button');if(b)b.style.setProperty('background-color',colors.correct,'important');});if(question.incorrectAnswers)question.incorrectAnswers.forEach(a=>{const b=FindByAttributeValue('data-functional-selector','answer-'+a,'button')||FindByAttributeValue('data-functional-selector','multi-select-button-'+a,'button');if(b)b.style.setProperty('background-color',colors.incorrect,'important');});}
    const quizIdSection=createSection('QUIZ ID'),quizIdInput=createInput('Enter Quiz ID...');quizIdSection.body.appendChild(quizIdInput);content.appendChild(quizIdSection.section);
    const pointsSection=createSection('POINTS PER QUESTION'),pointsSlider=createSlider(500,1000,950);pointsSection.body.appendChild(pointsSlider.container);content.appendChild(pointsSection.section);
    const answeringSection=createSection('ANSWERING');answeringSection.body.appendChild(createToggle('Auto Answer',autoAnswer,c=>{autoAnswer=c;info.ILSetQuestion=info.questionNum;}));answeringSection.body.appendChild(createToggle('Show Answers',showAnswers,c=>{showAnswers=c;if(!showAnswers&&!isAltSPressed)resetAnswerColors();}));content.appendChild(answeringSection.section);
    const rainbowSection=createSection('RAINBOW MODE'),rainbowSlider=createSlider(50,1000,300);rainbowSection.body.appendChild(rainbowSlider.container);rainbowSection.body.appendChild(createButton('Toggle Rainbow',()=>rainbowInterval?stopRainbowEffect():startRainbowEffect()));content.appendChild(rainbowSection.section);
    const keybindsSection=createSection('KEYBINDS');[['ALT + H','Toggle UI'],['ALT + W','Correct answer'],['ALT + S','Show answers'],['ALT + R','Rainbow mode'],['Shift','Quick hide']].forEach(([key,desc])=>{const row=document.createElement('div');Object.assign(row.style,{display:'flex',justifyContent:'space-between',margin:'6px 0',fontSize:'13px'});row.innerHTML=`<span style="color:${colors.accent};font-weight:bold">${key}</span><span>${desc}</span>`;keybindsSection.body.appendChild(row);});content.appendChild(keybindsSection.section);
    const infoSection=createSection('INFO'),questionsLabel=document.createElement('div'),inputLagLabel=document.createElement('div'),versionLabel=document.createElement('div');questionsLabel.textContent='Question: 0/0';questionsLabel.style.margin='5px 0';inputLagLabel.textContent='Input lag: 100ms';inputLagLabel.style.margin='5px 0';versionLabel.textContent=`Version: ${Version}`;versionLabel.style.margin='5px 0';infoSection.body.append(questionsLabel,inputLagLabel,versionLabel);content.appendChild(infoSection.section);
    const credit=document.createElement('div');credit.textContent='made by the owner of ubg43';Object.assign(credit.style,{color:'rgba(240,240,255,0.7)',fontSize:'11px',textAlign:'center',padding:'4px 0 10px',flexShrink:'0'});content.appendChild(credit);uiElement.appendChild(content);document.body.appendChild(uiElement);
    let dragData=null;header.addEventListener('mousedown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='BUTTON')return;dragData={startX:e.clientX,startY:e.clientY,offsetX:e.clientX-uiElement.offsetLeft,offsetY:e.clientY-uiElement.offsetTop,dragging:false};e.preventDefault();});document.addEventListener('mousemove',e=>{if(!dragData)return;const dx=Math.abs(e.clientX-dragData.startX),dy=Math.abs(e.clientY-dragData.startY);if(!dragData.dragging&&(dx>5||dy>5)){dragData.dragging=true;uiElement.style.cursor='grabbing';uiElement.style.userSelect='none';}if(dragData.dragging){uiElement.style.left=`${Math.max(0,Math.min(window.innerWidth-uiElement.offsetWidth,e.clientX-dragData.offsetX))}px`;uiElement.style.top=`${Math.max(0,Math.min(window.innerHeight-uiElement.offsetHeight,e.clientY-dragData.offsetY))}px`;}});document.addEventListener('mouseup',()=>{if(dragData){uiElement.style.cursor='';uiElement.style.userSelect='';dragData=null;}});
    let isMinimized=false;minimizeBtn.addEventListener('click',()=>{isMinimized=!isMinimized;content.style.display=isMinimized?'none':'flex';minimizeBtn.textContent=isMinimized?'+':'─';});closeBtn.addEventListener('click',()=>{uiElement.remove();autoAnswer=false;showAnswers=false;stopRainbowEffect();});
    quizIdInput.addEventListener('input',()=>{const quizID=quizIdInput.value.trim();if(!quizID){quizIdInput.style.borderColor=colors.accent;info.numQuestions=0;questionsLabel.textContent='Question: 0/0';return;}fetch(`https://kahoot.it/rest/kahoots/${quizID}`).then(r=>{if(!r.ok)throw new Error('Invalid');return r.json();}).then(data=>{quizIdInput.style.borderColor=colors.correct;questions=parseQuestions(data.questions);info.numQuestions=questions.length;questionsLabel.textContent=`Question: 0/${info.numQuestions}`;}).catch(()=>{quizIdInput.style.borderColor=colors.incorrect;info.numQuestions=0;questionsLabel.textContent='Question: 0/0';});});
    pointsSlider.slider.addEventListener('input',()=>{PPT=+pointsSlider.slider.value;pointsSlider.valueDisplay.textContent=PPT;});rainbowSlider.slider.addEventListener('input',()=>{rainbowSpeed=+rainbowSlider.slider.value;rainbowSlider.valueDisplay.textContent=`${rainbowSpeed}ms`;if(rainbowInterval)startRainbowEffect();});
    function parseQuestions(qs){return qs.map(q=>{const x={type:q.type,time:q.time};if(['quiz','multiple_select_quiz'].includes(q.type)){x.answers=[];x.incorrectAnswers=[];q.choices.forEach((c,i)=>(c.correct?x.answers:x.incorrectAnswers).push(i));}if(q.type==='open_ended')x.answers=q.choices.map(c=>c.answer);return x;});}
    function answer(q,time){Answered_PPT=PPT;const delay=q.type==='multiple_select_quiz'?60:0;setTimeout(()=>{if(q.type==='quiz')window.dispatchEvent(new KeyboardEvent('keydown',{key:(q.answers[0]+1).toString()}));else if(q.type==='multiple_select_quiz'){q.answers.forEach(a=>window.dispatchEvent(new KeyboardEvent('keydown',{key:(a+1).toString()})));setTimeout(()=>{const b=document.querySelector('[data-functional-selector="multi-select-submit-button"]');if(b)b.click();},50);}},time-delay);}
    function onQuestionStart(){const q=questions[info.questionNum];if(!q)return;if(showAnswers||isAltSPressed)highlightAnswers(q);if(autoAnswer){const t=(q.time-q.time/(500/(PPT-500)))-inputLag;answer(q,t);}}
    document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h'&&e.altKey){e.preventDefault();isAltHPressed=!isAltHPressed;uiElement.style.opacity=isAltHPressed?'0':'1';uiElement.style.pointerEvents=isAltHPressed?'none':'auto';}if(e.key==='Shift'&&!e.altKey){e.preventDefault();uiElement.style.opacity=uiElement.style.opacity==='0'?'1':'0';}if(e.key.toLowerCase()==='w'&&e.altKey&&info.questionNum!==-1){e.preventDefault();const q=questions[info.questionNum];if(!q?.answers)return;if(q.type==='quiz')window.dispatchEvent(new KeyboardEvent('keydown',{key:(q.answers[0]+1).toString()}));else if(q.type==='multiple_select_quiz'){q.answers.forEach(a=>window.dispatchEvent(new KeyboardEvent('keydown',{key:(a+1).toString()})));setTimeout(()=>{const b=document.querySelector('[data-functional-selector="multi-select-submit-button"]');if(b)b.click();},50);}}if(e.key.toLowerCase()==='s'&&e.altKey&&info.questionNum!==-1){e.preventDefault();isAltSPressed=true;highlightAnswers(questions[info.questionNum]);}if(e.key.toLowerCase()==='r'&&e.altKey){e.preventDefault();isAltRPressed=true;startRainbowEffect();}});document.addEventListener('keyup',e=>{if(e.key.toLowerCase()==='s'&&isAltSPressed){isAltSPressed=false;if(!showAnswers)resetAnswerColors();}if(e.key.toLowerCase()==='r'&&isAltRPressed){isAltRPressed=false;stopRainbowEffect();}});
    setInterval(()=>{const counter=document.querySelector('[data-functional-selector="question-index-counter"]');if(counter){info.questionNum=parseInt(counter.textContent)-1;questionsLabel.textContent=`Question: ${info.questionNum+1}/${info.numQuestions}`;}if(document.querySelector('[data-functional-selector^="answer-"]')&&info.lastAnsweredQuestion!==info.questionNum){info.lastAnsweredQuestion=info.questionNum;onQuestionStart();}if(autoAnswer&&info.ILSetQuestion!==info.questionNum){const el=document.querySelector('[data-functional-selector="score-increment"]');if(el){info.ILSetQuestion=info.questionNum;const inc=parseInt(el.textContent.split(' ')[1]);if(!isNaN(inc)){const ppt=Math.min(Answered_PPT,987),adjustment=(ppt-inc)*15;inputLag=Math.max(0,inputLag+adjustment);inputLagLabel.textContent=`Input lag: ${inputLag}ms`;}}}},50);
})();
